<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW0060" ignored="8" name="TestNgExample" tests="4" failures="3" timestamp="16 Mar 2018 08:06:46 GMT" time="0.064" errors="0">
  <testcase name="testSin" time="0.02" classname="com.epam.test.calculator.PositivTest"/>
  <testcase name="testCosn" time="0.017" classname="com.epam.test.calculator.NegativTests">
    <failure type="java.lang.AssertionError" message="expected [1999999998] but found [1.999999998E9]">
      <![CDATA[java.lang.AssertionError: expected [1999999998] but found [1.999999998E9]
at com.epam.test.calculator.NegativTests.testCosn(NegativTests.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testCosn -->
  <testcase name="testTg" time="0.024" classname="com.epam.test.calculator.PositivTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.epam.test.calculator.PositivTest.testTg(PositivTest.java:44)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testTg -->
  <testcase name="testCtg" time="0.036" classname="com.epam.test.calculator.PositivTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.epam.test.calculator.PositivTest.testCtg(PositivTest.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="sumTest" time="0.0" classname="com.epam.test.calculator.PositivTest">
    <ignored/>
  </testcase> <!-- sumTest -->
  <testcase name="testPow" time="0.0" classname="com.epam.test.calculator.NegativTests">
    <ignored/>
  </testcase> <!-- testPow -->
  <testcase name="testSin" time="0.0" classname="com.epam.test.calculator.NegativTests">
    <ignored/>
  </testcase> <!-- testSin -->
  <testcase name="testTg" time="0.0" classname="com.epam.test.calculator.NegativTests">
    <ignored/>
  </testcase> <!-- testTg -->
  <testcase name="testCos" time="0.0" classname="com.epam.test.calculator.NegativTests">
    <ignored/>
  </testcase> <!-- testCos -->
  <testcase name="testPow" time="0.0" classname="com.epam.test.calculator.PositivTest">
    <ignored/>
  </testcase> <!-- testPow -->
  <testcase name="testSinNeg" time="0.0" classname="com.epam.test.calculator.NegativTests">
    <ignored/>
  </testcase> <!-- testSinNeg -->
  <testcase name="testCtg" time="0.0" classname="com.epam.test.calculator.NegativTests">
    <ignored/>
  </testcase> <!-- testCtg -->
</testsuite> <!-- TestNgExample -->
