<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPRURYAW0060" name="com.epam.test.calculator.suites.test.positive.BasicOperators" tests="16" failures="3" timestamp="19 Mar 2018 12:49:05 GMT" time="0.057" errors="0">
  <testcase name="testPow" time="0.001" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="testPow" time="0.001" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="multTest" time="0.009" classname="com.epam.test.calculator.suites.test.positive.BasicOperators">
    <failure type="java.lang.AssertionError" message="expected [3.92351654564654] but found [3.0]">
      <![CDATA[java.lang.AssertionError: expected [3.92351654564654] but found [3.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.epam.test.calculator.suites.test.positive.BasicOperators.multTest(BasicOperators.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- multTest -->
  <testcase name="testPow" time="0.001" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="testPow" time="0.009" classname="com.epam.test.calculator.suites.test.positive.BasicOperators">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.epam.test.calculator.suites.test.positive.BasicOperators.testPow(BasicOperators.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testPow -->
  <testcase name="divTest" time="0.003" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="testIsPositive" time="0.006" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="divTest" time="0.001" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="divTest" time="0.001" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="multTest" time="0.009" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="divTest" time="0.006" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="divTest" time="0.004" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="multTest" time="0.003" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="testPow" time="0.002" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
  <testcase name="multTest" time="0.000" classname="com.epam.test.calculator.suites.test.positive.BasicOperators">
    <failure type="java.lang.AssertionError" message="expected [-3000.6000000000004] but found [-3001.0]">
      <![CDATA[java.lang.AssertionError: expected [-3000.6000000000004] but found [-3001.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.epam.test.calculator.suites.test.positive.BasicOperators.multTest(BasicOperators.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- multTest -->
  <testcase name="multTest" time="0.001" classname="com.epam.test.calculator.suites.test.positive.BasicOperators"/>
</testsuite> <!-- com.epam.test.calculator.suites.test.positive.BasicOperators -->
